// =====================================================
// Data Access Layer — the spreadsheet-generated JSON is
// the single source of truth (regenerated by etl/build_data.py)
// =====================================================
import raw from '../data/laptops.json'

export interface Display {
  sizeInches: number | null
  resolution: string | null
  resW: number | null
  resH: number | null
  ppi: number | null
  resClass: string | null
  refreshHz: number | null
  panel: string | null
  touch: boolean
}
export interface Cpu {
  brand: string | null
  model: string | null
  cores: number | null
  multiThread: boolean
  passmark: number | null
}
export interface Gpu {
  kind: string
  dedicated: boolean
  brand: string | null
  model: string | null
  g3dmark: number | null
}
export interface Scores {
  overall: number; gaming: number; office: number; programming: number
  engineering: number; creator: number; student: number; travel: number
  ai: number; value: number
}
export interface Laptop {
  id: number
  slug: string
  name: string
  brand: string
  model: string
  segment: string
  formFactor: string
  priceBracket: string | null
  price: number
  display: Display
  cpu: Cpu
  gpu: Gpu
  ram: { gb: number | null; type: string | null; soldered: boolean }
  storage: { gb: number | null; type: string | null; raw: string }
  physical: { thicknessIn: number | null; lengthIn: number | null; widthIn: number | null; weightLbs: number | null; weightKg: number | null }
  amazon: { url: string | null; rating: number | null; reviewCount: number | null }
  scores: Scores
  badges: string[]
}

const db = raw as unknown as { meta: { updated: string; count: number; affiliateDisclosure: string }, laptops: Laptop[] }

export const META = db.meta
export const LAPTOPS: Laptop[] = db.laptops
const bySlugMap = new Map(LAPTOPS.map(l => [l.slug, l]))

export const all = () => LAPTOPS
export const bySlug = (slug: string) => bySlugMap.get(slug)
export const byId = (id: number) => LAPTOPS.find(l => l.id === id)

export const cpuLabel = (l: Laptop) => [l.cpu.brand, l.cpu.model].filter(Boolean).join(' ').trim() || 'N/A'
export const gpuLabel = (l: Laptop) =>
  l.gpu.dedicated ? [l.gpu.brand, l.gpu.model].filter(Boolean).join(' ') : `Integrated (${l.cpu.brand || ''} iGPU)`.trim()
export const gpuShort = (l: Laptop) => l.gpu.dedicated ? (l.gpu.model || 'Dedicated') : 'Integrated'
export const money = (n: number) => '$' + (Math.round(n) === n ? n.toLocaleString('en-US') : n.toLocaleString('en-US', { minimumFractionDigits: 2 }))
export const storageLabel = (l: Laptop) => l.storage.gb ? (l.storage.gb >= 1024 ? `${l.storage.gb / 1024} TB` : `${l.storage.gb} GB`) + ` ${l.storage.type || ''}`.trim() : l.storage.raw
